### ISSUE TITLE
generate pdf ? 

### ISSUE THREAD

**Issue by frelle** [eissapk/cv-builder#1]
Hello,

How to generate a pdf after fill out all the data ? 

Thank you

**Comment by eissapk** [comment]
Actually, the app generates HTML file as A4 paper size which can be printed anywhere but if you really want the pdf version I recommend you to use desktop google chrome which generates PDF.
Steps in chrome after clicking DONE button there will be a popup window:
1- click print cv
2- select from the destination dropdown menu "save as PDF"
3- uncheck headers and footers "option"
4- check background graphics "option"

**Comment by frelle** [comment]
Thank you for your answer. It's a great design!

**Comment by frelle** [comment]
Thank you for your answer. It's a great design!
